spring.datasource.url=jdbc:postgresql://localhost:5432/meetingmind
spring.datasource.username=suaybboncuk
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=meetingmind
server.port=8080
gemini.api.key=AIzaSyDunEpcS2-6xIVJdKDJIs4nMoBi2v9buBM


